package net.sf.bse.gui;

/*
 * Copyright (c) 2002-2003 BSE project contributors 
 * (http://bse.sourceforge.net/)
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * The GUI was created using NetBeans IDE (http://www.netbeans.org/).
 * Please use the NetBeans GUI editor if you wish to modify it.
 *
 * @author Aleksi Peebles (aleksi.peebles@infocast.fi)
 * @version $Revision: 1.3 $ $Date: 2004/05/06 10:08:14 $
 */
public class BSEGUI extends javax.swing.JFrame
{
    private javax.swing.JFileChooser chooser;
    private XletTree xletTree;
    
    public BSEGUI()
    {
        initComponents();
        xletTree = new XletTree();
        treeScrollPane.setViewportView(xletTree);
        chooser = new javax.swing.JFileChooser();
        setSize(new java.awt.Dimension(640, 480));
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        xletTabPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        treeScrollPane = new javax.swing.JScrollPane();
        xletSelectRootButton = new javax.swing.JButton();
        xletRecursiveCheckBox = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xletCertList = new javax.swing.JList();
        xletCertList.setModel(new javax.swing.DefaultListModel());
        xletCertList.setCellRenderer(new XletListCellRenderer());
        jPanel18 = new javax.swing.JPanel();
        xletAddCertButton = new javax.swing.JButton();
        xletRemoveCertButton = new javax.swing.JButton();
        xletCertUpButton = new javax.swing.JButton();
        xletCertDownButton = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        xletPrivateKeyFileTextField = new javax.swing.JTextField();
        xletPrivateKeyFileButton = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        xletDestinationDirTextField = new javax.swing.JTextField();
        xletDestinationDirButton = new javax.swing.JButton();
        xletDeleteDestDirCheckBox = new javax.swing.JCheckBox();
        xletSignButton = new javax.swing.JButton();
        rootTabPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rootFileTextField = new javax.swing.JTextField();
        rootFileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rootNameTextField = new javax.swing.JTextField();
        rootCountryTextField = new javax.swing.JTextField();
        rootEmailTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rootSerialTextField = new javax.swing.JTextField();
        rootStrengthComboBox = new javax.swing.JComboBox();
        rootStrengthComboBox.addItem("512");
        rootStrengthComboBox.addItem("1024");
        rootStrengthComboBox.addItem("2048");
        rootStrengthComboBox.addItem("4096");
        rootStrengthComboBox.setSelectedIndex(1);
        jPanel5 = new javax.swing.JPanel();
        rootFromDDTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rootFromMMTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rootFromYYYYTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rootUntilDDTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rootUntilMMTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rootUntilYYYYTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rootGenerateButton = new javax.swing.JButton();
        requestTabPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        requestFileTextField = new javax.swing.JTextField();
        requestFileButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        requestNameTextField = new javax.swing.JTextField();
        requestCountryTextField = new javax.swing.JTextField();
        requestEmailTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        requestOrgIDTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        requestUntilDDTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        requestUntilMMTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        requestUntilYYYYTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        requestFromDDTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        requestFromMMTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        requestFromYYYYTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        requestStrengthComboBox = new javax.swing.JComboBox();
        requestStrengthComboBox.addItem("512");
        requestStrengthComboBox.addItem("1024");
        requestStrengthComboBox.addItem("2048");
        requestStrengthComboBox.addItem("4096");
        requestStrengthComboBox.setSelectedIndex(1);
        requestGenerateButton = new javax.swing.JButton();
        signTabPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        signCertificateFileTextField = new javax.swing.JTextField();
        signCertificateFileButton = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        signPrivateKeyFileTextField = new javax.swing.JTextField();
        signPrivateKeyFileButton = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        signFileTextField = new javax.swing.JTextField();
        signFileButton = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        signRequestFileTextField = new javax.swing.JTextField();
        signRequestFileButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        signFromDDTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        signFromMMTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        signFromYYYYTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        signUntilDDTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        signUntilMMTextField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        signUntilYYYYTextField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();

        setTitle("Broadcast Signing Engine");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });

        xletTabPanel.setLayout(new java.awt.GridBagLayout());

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel33.setText("Sign Xlet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        xletTabPanel.add(jLabel33, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel17.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel17.add(treeScrollPane, gridBagConstraints);

        xletSelectRootButton.setText("Select Root");
        xletSelectRootButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletSelectRootButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel17.add(xletSelectRootButton, gridBagConstraints);

        xletRecursiveCheckBox.setSelected(true);
        xletRecursiveCheckBox.setText("Recursive Selection");
        xletRecursiveCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletRecursiveCheckBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel17.add(xletRecursiveCheckBox, gridBagConstraints);

        jPanel16.add(jPanel17);

        jPanel19.setLayout(new java.awt.GridBagLayout());

        jPanel23.setLayout(new java.awt.GridBagLayout());

        jPanel20.setLayout(new java.awt.GridBagLayout());

        jPanel20.setBorder(new javax.swing.border.TitledBorder("Certificate Files"));
        xletCertList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        xletCertList.setToolTipText("List of certificate files in the certificate chain. \nThe files must be in the correct ascending order: \nsigning certificate first and root certificate last.");
        xletCertList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                xletCertListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(xletCertList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel20.add(jScrollPane1, gridBagConstraints);

        jPanel18.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        xletAddCertButton.setText("Add");
        xletAddCertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletAddCertButtonActionPerformed(evt);
            }
        });

        jPanel18.add(xletAddCertButton);

        xletRemoveCertButton.setText("Remove");
        xletRemoveCertButton.setEnabled(false);
        xletRemoveCertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletRemoveCertButtonActionPerformed(evt);
            }
        });

        jPanel18.add(xletRemoveCertButton);

        xletCertUpButton.setText("Up");
        xletCertUpButton.setEnabled(false);
        xletCertUpButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletCertUpButtonActionPerformed(evt);
            }
        });

        jPanel18.add(xletCertUpButton);

        xletCertDownButton.setText("Down");
        xletCertDownButton.setEnabled(false);
        xletCertDownButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletCertDownButtonActionPerformed(evt);
            }
        });

        jPanel18.add(xletCertDownButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel20.add(jPanel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel23.add(jPanel20, gridBagConstraints);

        jLabel48.setText("Private Key File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel23.add(jLabel48, gridBagConstraints);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel21.add(xletPrivateKeyFileTextField, gridBagConstraints);

        xletPrivateKeyFileButton.setText("...");
        xletPrivateKeyFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletPrivateKeyFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel21.add(xletPrivateKeyFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel23.add(jPanel21, gridBagConstraints);

        jPanel24.setLayout(new java.awt.GridBagLayout());

        jPanel24.setBorder(new javax.swing.border.TitledBorder("Destination Directory"));
        jPanel22.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel22.add(xletDestinationDirTextField, gridBagConstraints);

        xletDestinationDirButton.setText("...");
        xletDestinationDirButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletDestinationDirButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel22.add(xletDestinationDirButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel24.add(jPanel22, gridBagConstraints);

        xletDeleteDestDirCheckBox.setText("Remove If Exists");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel24.add(xletDeleteDestDirCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel23.add(jPanel24, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel19.add(jPanel23, gridBagConstraints);

        jPanel16.add(jPanel19);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        xletTabPanel.add(jPanel16, gridBagConstraints);

        xletSignButton.setText("Sign");
        xletSignButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                xletSignButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        xletTabPanel.add(xletSignButton, gridBagConstraints);

        jTabbedPane1.addTab("Sign Xlet", xletTabPanel);

        rootTabPanel.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel15.setText("Generate Root Certificate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rootTabPanel.add(jLabel15, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(rootFileTextField, gridBagConstraints);

        rootFileButton.setText("...");
        rootFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rootFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(rootFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel2.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Country:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(rootNameTextField, gridBagConstraints);

        rootCountryTextField.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(rootCountryTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(rootEmailTextField, gridBagConstraints);

        jLabel5.setText("Valid from:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Valid until:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Serial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Strength:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(rootSerialTextField, gridBagConstraints);

        rootStrengthComboBox.setEditable(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(rootStrengthComboBox, gridBagConstraints);

        rootFromDDTextField.setColumns(2);
        jPanel5.add(rootFromDDTextField);

        jLabel9.setText("/");
        jPanel5.add(jLabel9);

        rootFromMMTextField.setColumns(2);
        jPanel5.add(rootFromMMTextField);

        jLabel10.setText("/");
        jPanel5.add(jLabel10);

        rootFromYYYYTextField.setColumns(4);
        jPanel5.add(rootFromYYYYTextField);

        jLabel11.setText("(dd/mm/yyyy)");
        jPanel5.add(jLabel11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(jPanel5, gridBagConstraints);

        rootUntilDDTextField.setColumns(2);
        jPanel6.add(rootUntilDDTextField);

        jLabel12.setText("/");
        jPanel6.add(jLabel12);

        rootUntilMMTextField.setColumns(2);
        jPanel6.add(rootUntilMMTextField);

        jLabel13.setText("/");
        jPanel6.add(jLabel13);

        rootUntilYYYYTextField.setColumns(4);
        jPanel6.add(rootUntilYYYYTextField);

        jLabel14.setText("(dd/mm/yyyy)");
        jPanel6.add(jLabel14);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        rootTabPanel.add(jPanel1, gridBagConstraints);

        rootGenerateButton.setText("Generate");
        rootGenerateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rootGenerateButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        rootTabPanel.add(rootGenerateButton, gridBagConstraints);

        jTabbedPane1.addTab("Generate Root", rootTabPanel);

        requestTabPanel.setLayout(new java.awt.GridBagLayout());

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel23.setText("Generate Leaf Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        requestTabPanel.add(jLabel23, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel16.setText("File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel16, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(requestFileTextField, gridBagConstraints);

        requestFileButton.setText("...");
        requestFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                requestFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel4.add(requestFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jPanel4, gridBagConstraints);

        jLabel17.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel17, gridBagConstraints);

        jLabel18.setText("Country:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel18, gridBagConstraints);

        jLabel19.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel19, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(requestNameTextField, gridBagConstraints);

        requestCountryTextField.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(requestCountryTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(requestEmailTextField, gridBagConstraints);

        jLabel20.setText("Valid from:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Valid until:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel21, gridBagConstraints);

        jLabel22.setText("Org. Text + '.' + 8-digit hex Org. ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jLabel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(requestOrgIDTextField, gridBagConstraints);

        requestUntilDDTextField.setColumns(2);
        jPanel8.add(requestUntilDDTextField);

        jLabel27.setText("/");
        jPanel8.add(jLabel27);

        requestUntilMMTextField.setColumns(2);
        jPanel8.add(requestUntilMMTextField);

        jLabel28.setText("/");
        jPanel8.add(jLabel28);

        requestUntilYYYYTextField.setColumns(4);
        jPanel8.add(requestUntilYYYYTextField);

        jLabel29.setText("(dd/mm/yyyy)");
        jPanel8.add(jLabel29);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(jPanel8, gridBagConstraints);

        requestFromDDTextField.setColumns(2);
        jPanel7.add(requestFromDDTextField);

        jLabel24.setText("/");
        jPanel7.add(jLabel24);

        requestFromMMTextField.setColumns(2);
        jPanel7.add(requestFromMMTextField);

        jLabel25.setText("/");
        jPanel7.add(jLabel25);

        requestFromYYYYTextField.setColumns(4);
        jPanel7.add(requestFromYYYYTextField);

        jLabel26.setText("(dd/mm/yyyy)");
        jPanel7.add(jLabel26);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel3.add(jPanel7, gridBagConstraints);

        jLabel30.setText("Strength:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel30, gridBagConstraints);

        requestStrengthComboBox.setEditable(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(requestStrengthComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        requestTabPanel.add(jPanel3, gridBagConstraints);

        requestGenerateButton.setText("Generate");
        requestGenerateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                requestGenerateButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        requestTabPanel.add(requestGenerateButton, gridBagConstraints);

        jTabbedPane1.addTab("Generate Request", requestTabPanel);

        signTabPanel.setLayout(new java.awt.GridBagLayout());

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel32.setText("Sign Leaf Certificate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        signTabPanel.add(jLabel32, gridBagConstraints);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel34.setText("Certificate File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel9.add(jLabel34, gridBagConstraints);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel10.add(signCertificateFileTextField, gridBagConstraints);

        signCertificateFileButton.setText("...");
        signCertificateFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signCertificateFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel10.add(signCertificateFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel9.add(jPanel10, gridBagConstraints);

        jLabel35.setText("Private Key File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel9.add(jLabel35, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel11.add(signPrivateKeyFileTextField, gridBagConstraints);

        signPrivateKeyFileButton.setText("...");
        signPrivateKeyFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signPrivateKeyFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel11.add(signPrivateKeyFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel9.add(jPanel11, gridBagConstraints);

        jLabel36.setText("File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel9.add(jLabel36, gridBagConstraints);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel12.add(signFileTextField, gridBagConstraints);

        signFileButton.setText("...");
        signFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel12.add(signFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel9.add(jPanel12, gridBagConstraints);

        jLabel37.setText("Request File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel9.add(jLabel37, gridBagConstraints);

        jPanel13.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel13.add(signRequestFileTextField, gridBagConstraints);

        signRequestFileButton.setText("...");
        signRequestFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signRequestFileButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel13.add(signRequestFileButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel9.add(jPanel13, gridBagConstraints);

        signFromDDTextField.setColumns(2);
        jPanel14.add(signFromDDTextField);

        jLabel38.setText("/");
        jPanel14.add(jLabel38);

        signFromMMTextField.setColumns(2);
        jPanel14.add(signFromMMTextField);

        jLabel39.setText("/");
        jPanel14.add(jLabel39);

        signFromYYYYTextField.setColumns(4);
        jPanel14.add(signFromYYYYTextField);

        jLabel40.setText("(dd/mm/yyyy)");
        jPanel14.add(jLabel40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel9.add(jPanel14, gridBagConstraints);

        signUntilDDTextField.setColumns(2);
        jPanel15.add(signUntilDDTextField);

        jLabel41.setText("/");
        jPanel15.add(jLabel41);

        signUntilMMTextField.setColumns(2);
        jPanel15.add(signUntilMMTextField);

        jLabel42.setText("/");
        jPanel15.add(jLabel42);

        signUntilYYYYTextField.setColumns(4);
        jPanel15.add(signUntilYYYYTextField);

        jLabel43.setText("(dd/mm/yyyy)");
        jPanel15.add(jLabel43);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel9.add(jPanel15, gridBagConstraints);

        jLabel44.setText("Valid from:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel9.add(jLabel44, gridBagConstraints);

        jLabel45.setText("Valid until:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel9.add(jLabel45, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        signTabPanel.add(jPanel9, gridBagConstraints);

        signButton.setText("Sign");
        signButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        signTabPanel.add(signButton, gridBagConstraints);

        jTabbedPane1.addTab("Sign Certificate", signTabPanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void xletCertListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_xletCertListValueChanged
    {//GEN-HEADEREND:event_xletCertListValueChanged
        if (xletCertList.getSelectedIndex() != -1)
        {
            xletRemoveCertButton.setEnabled(true);
            xletCertUpButton.setEnabled(true);
            xletCertDownButton.setEnabled(true);
        }
        else
        {
            xletRemoveCertButton.setEnabled(false);
            xletCertUpButton.setEnabled(false);
            xletCertDownButton.setEnabled(false);
        }            
    }//GEN-LAST:event_xletCertListValueChanged

    private void xletDestinationDirButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletDestinationDirButtonActionPerformed
    {//GEN-HEADEREND:event_xletDestinationDirButtonActionPerformed
        directoryChooserButtonActionPerformed(
            "Select Destination Directory", xletDestinationDirTextField);
    }//GEN-LAST:event_xletDestinationDirButtonActionPerformed

    private void xletPrivateKeyFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletPrivateKeyFileButtonActionPerformed
    {//GEN-HEADEREND:event_xletPrivateKeyFileButtonActionPerformed
        fileChooserButtonActionPerformed(
            "Select Private Key File", xletPrivateKeyFileTextField);
    }//GEN-LAST:event_xletPrivateKeyFileButtonActionPerformed

    private void xletCertDownButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletCertDownButtonActionPerformed
    {//GEN-HEADEREND:event_xletCertDownButtonActionPerformed
        int index = xletCertList.getSelectedIndex();
        javax.swing.DefaultListModel model = 
            (javax.swing.DefaultListModel)xletCertList.getModel();
        if (index < model.size() - 1)
        {
            model.add(index + 1, model.remove(index));
            xletCertList.setSelectedIndex(index + 1);
        }
        else
        {
            xletCertList.setSelectedIndex(index);
        }        
    }//GEN-LAST:event_xletCertDownButtonActionPerformed

    private void xletCertUpButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletCertUpButtonActionPerformed
    {//GEN-HEADEREND:event_xletCertUpButtonActionPerformed
        int index = xletCertList.getSelectedIndex();
        if (index > 0)
        {
            javax.swing.DefaultListModel model = 
                (javax.swing.DefaultListModel)xletCertList.getModel();
            model.add(index - 1, model.remove(index));
            xletCertList.setSelectedIndex(index - 1);
        }
        else
        {
            xletCertList.setSelectedIndex(index);
        }        
    }//GEN-LAST:event_xletCertUpButtonActionPerformed

    private void xletRemoveCertButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletRemoveCertButtonActionPerformed
    {//GEN-HEADEREND:event_xletRemoveCertButtonActionPerformed
        ((javax.swing.DefaultListModel)xletCertList.getModel()).
            remove(xletCertList.getSelectedIndex());        
    }//GEN-LAST:event_xletRemoveCertButtonActionPerformed

    private void xletAddCertButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletAddCertButtonActionPerformed
    {//GEN-HEADEREND:event_xletAddCertButtonActionPerformed
        fileChooserButtonActionPerformed(
            "Select Certificate File To Add", xletCertList);
    }//GEN-LAST:event_xletAddCertButtonActionPerformed

    private void xletSignButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletSignButtonActionPerformed
    {//GEN-HEADEREND:event_xletSignButtonActionPerformed
        java.io.File destDir = 
            new java.io.File(xletDestinationDirTextField.getText());
        if (destDir.exists() && !xletDeleteDestDirCheckBox.isSelected())
        {
            int option = javax.swing.JOptionPane.showConfirmDialog(this, 
                "The destination directory exists and will be removed.\n" +
                "Do you want to continue?", 
                "Remove Existing Directory?", 
                javax.swing.JOptionPane.YES_NO_OPTION);
            if (option == javax.swing.JOptionPane.NO_OPTION)
            {
                return;
            }
        }
        
        Object[] certFiles = 
            ((javax.swing.DefaultListModel)xletCertList.getModel()).toArray();
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < certFiles.length; i++)
        {
            sb.append(((java.io.File)certFiles[i]).getAbsolutePath());
            if (i < certFiles.length - 1)
            {
                sb.append(java.io.File.pathSeparatorChar);
            }            
        }
        String certs = sb.toString();
        
        String[] signFileNames = xletTree.getSignFileNames();        
        sb = new StringBuffer();
        for (int i = 0; i < signFileNames.length; i++)
        {
            sb.append(signFileNames[i]);
            if (i < signFileNames.length - 1)
            {
                sb.append(java.io.File.pathSeparatorChar);
            }
        }
        String files = sb.toString();
                
        java.util.HashMap arguments = new java.util.HashMap();

        arguments.put("certs:", certs);
        arguments.put("key:", xletPrivateKeyFileTextField.getText());
        arguments.put("src:", xletTree.getRoot().getAbsolutePath());
        arguments.put("dest:", xletDestinationDirTextField.getText());
        arguments.put("files:", files);
        arguments.put("rm:", "true");
        
        net.sf.bse.Command command = new net.sf.bse.SignXlet(arguments);
        try
        {
            command.run();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }                
    }//GEN-LAST:event_xletSignButtonActionPerformed

    private void xletRecursiveCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletRecursiveCheckBoxActionPerformed
    {//GEN-HEADEREND:event_xletRecursiveCheckBoxActionPerformed
        xletTree.setRecursiveSelection(xletRecursiveCheckBox.isSelected());
    }//GEN-LAST:event_xletRecursiveCheckBoxActionPerformed

    private void xletSelectRootButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xletSelectRootButtonActionPerformed
    {//GEN-HEADEREND:event_xletSelectRootButtonActionPerformed
        chooser.setDialogTitle("Select New Root Directory");
        chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) 
        {
            xletTree.setRoot(
                new java.io.File(chooser.getSelectedFile().getAbsolutePath()));
        }        
    }//GEN-LAST:event_xletSelectRootButtonActionPerformed

    private void signRequestFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signRequestFileButtonActionPerformed
    {//GEN-HEADEREND:event_signRequestFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select Request File", 
            signRequestFileTextField);
    }//GEN-LAST:event_signRequestFileButtonActionPerformed

    private void signCertificateFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signCertificateFileButtonActionPerformed
    {//GEN-HEADEREND:event_signCertificateFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select Certificate File", 
            signCertificateFileTextField);
    }//GEN-LAST:event_signCertificateFileButtonActionPerformed

    private void signPrivateKeyFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signPrivateKeyFileButtonActionPerformed
    {//GEN-HEADEREND:event_signPrivateKeyFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select Private Key File", 
            signPrivateKeyFileTextField);
    }//GEN-LAST:event_signPrivateKeyFileButtonActionPerformed

    private void signFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signFileButtonActionPerformed
    {//GEN-HEADEREND:event_signFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select File To Save", 
            signFileTextField);
    }//GEN-LAST:event_signFileButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signButtonActionPerformed
    {//GEN-HEADEREND:event_signButtonActionPerformed
        java.util.HashMap arguments = new java.util.HashMap();

        arguments.put("csrFile:", signRequestFileTextField.getText());
        arguments.put("file:", signFileTextField.getText());
        arguments.put("certFile:", signCertificateFileTextField.getText());
        arguments.put("keyFile:", signPrivateKeyFileTextField.getText());        
        arguments.put("validFrom:", 
            signFromDDTextField.getText() + "/" + 
            signFromMMTextField.getText() + "/" + 
            signFromYYYYTextField.getText());
        arguments.put("validUntil:", 
            signUntilDDTextField.getText() + "/" + 
            signUntilMMTextField.getText() + "/" + 
            signUntilYYYYTextField.getText());
        
        net.sf.bse.Command command = 
            new net.sf.bse.SignLeafCertificate(arguments);
        try
        {
            command.run();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_signButtonActionPerformed

    private void requestFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_requestFileButtonActionPerformed
    {//GEN-HEADEREND:event_requestFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select File To Save", 
            requestFileTextField);
    }//GEN-LAST:event_requestFileButtonActionPerformed

    private void requestGenerateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_requestGenerateButtonActionPerformed
    {//GEN-HEADEREND:event_requestGenerateButtonActionPerformed
        java.util.HashMap arguments = new java.util.HashMap();

        arguments.put("file:", requestFileTextField.getText());
        arguments.put("name:", requestNameTextField.getText());
        arguments.put("country:", requestCountryTextField.getText());
        arguments.put("email:", requestEmailTextField.getText());
        arguments.put("org:", requestOrgIDTextField.getText());
        arguments.put("validFrom:", 
            requestFromDDTextField.getText() + "/" + 
            requestFromMMTextField.getText() + "/" + 
            requestFromYYYYTextField.getText());
        arguments.put("validUntil:", 
            requestUntilDDTextField.getText() + "/" + 
            requestUntilMMTextField.getText() + "/" + 
            requestUntilYYYYTextField.getText());
        arguments.put("strength:", 
            requestStrengthComboBox.getSelectedItem().toString());
        
        net.sf.bse.Command command = 
            new net.sf.bse.GenerateLeafRequest(arguments);
        try
        {
            command.run();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_requestGenerateButtonActionPerformed

    private void rootGenerateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rootGenerateButtonActionPerformed
    {//GEN-HEADEREND:event_rootGenerateButtonActionPerformed
        java.util.HashMap arguments = new java.util.HashMap();
        
        arguments.put("file:", rootFileTextField.getText());
        arguments.put("name:", rootNameTextField.getText());
        arguments.put("country:", rootCountryTextField.getText());
        arguments.put("email:", rootEmailTextField.getText());
        arguments.put("validFrom:", 
            rootFromDDTextField.getText() + "/" + 
            rootFromMMTextField.getText() + "/" + 
            rootFromYYYYTextField.getText());
        arguments.put("validUntil:", 
            rootUntilDDTextField.getText() + "/" + 
            rootUntilMMTextField.getText() + "/" + 
            rootUntilYYYYTextField.getText());
        arguments.put("serial:", rootSerialTextField.getText());
        arguments.put("strength:", 
            rootStrengthComboBox.getSelectedItem().toString());
        
        net.sf.bse.Command command = 
            new net.sf.bse.GenerateRootCertificate(arguments);
        try
        {
            command.run();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rootGenerateButtonActionPerformed

    private void rootFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rootFileButtonActionPerformed
    {//GEN-HEADEREND:event_rootFileButtonActionPerformed
        fileChooserButtonActionPerformed("Select File To Save", 
            rootFileTextField);
    }//GEN-LAST:event_rootFileButtonActionPerformed
    
    private void directoryChooserButtonActionPerformed(
        String dialogTitle, javax.swing.JTextField textField)
    {
        chooser.setDialogTitle(dialogTitle);
        chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) 
        {
            textField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }
    
    private void fileChooserButtonActionPerformed(
        String dialogTitle, javax.swing.JTextField textField)
    {        
        chooser.setDialogTitle(dialogTitle);
        chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) 
        {
            textField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }
    
    private void fileChooserButtonActionPerformed(
        String dialogTitle, javax.swing.JList list)
    {        
        chooser.setDialogTitle(dialogTitle);
        chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(true);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) 
        {
            java.io.File[] files = chooser.getSelectedFiles();
            for (int i = 0; i < files.length; i++)
            {
                ((javax.swing.DefaultListModel)list.getModel()).addElement(
                    files[i]);
            }
        }
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new BSEGUI().show();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField signPrivateKeyFileTextField;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JTextField rootUntilDDTextField;
    private javax.swing.JCheckBox xletDeleteDestDirCheckBox;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JTextField requestFromMMTextField;
    private javax.swing.JComboBox requestStrengthComboBox;
    private javax.swing.JButton xletPrivateKeyFileButton;
    private javax.swing.JList xletCertList;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JTextField requestUntilMMTextField;
    private javax.swing.JTextField signCertificateFileTextField;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField rootNameTextField;
    private javax.swing.JPanel xletTabPanel;
    private javax.swing.JTextField xletDestinationDirTextField;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JButton xletDestinationDirButton;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField signFromDDTextField;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JTextField signFromYYYYTextField;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton requestFileButton;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField rootUntilYYYYTextField;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JComboBox rootStrengthComboBox;
    private javax.swing.JTextField requestFromYYYYTextField;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField signRequestFileTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField signUntilMMTextField;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JButton signButton;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton requestGenerateButton;
    private javax.swing.JTextField signUntilYYYYTextField;
    private javax.swing.JPanel signTabPanel;
    private javax.swing.JButton xletCertUpButton;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel rootTabPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JButton xletRemoveCertButton;
    private javax.swing.JTextField signFileTextField;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JButton rootGenerateButton;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JTextField signUntilDDTextField;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField rootSerialTextField;
    private javax.swing.JTextField rootFromYYYYTextField;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextField rootCountryTextField;
    private javax.swing.JTextField rootEmailTextField;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JButton signRequestFileButton;
    private javax.swing.JButton signPrivateKeyFileButton;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JTextField requestFromDDTextField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JButton xletSelectRootButton;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JButton signFileButton;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JButton signCertificateFileButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JTextField rootFileTextField;
    private javax.swing.JTextField xletPrivateKeyFileTextField;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField requestOrgIDTextField;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField requestNameTextField;
    private javax.swing.JTextField signFromMMTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JButton xletCertDownButton;
    private javax.swing.JTextField requestFileTextField;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JTextField requestEmailTextField;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JTextField rootFromMMTextField;
    private javax.swing.JPanel requestTabPanel;
    private javax.swing.JButton xletSignButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JTextField requestUntilYYYYTextField;
    private javax.swing.JTextField rootUntilMMTextField;
    private javax.swing.JButton xletAddCertButton;
    private javax.swing.JTextField requestCountryTextField;
    private javax.swing.JTextField requestUntilDDTextField;
    private javax.swing.JButton rootFileButton;
    private javax.swing.JTextField rootFromDDTextField;
    private javax.swing.JCheckBox xletRecursiveCheckBox;
    private javax.swing.JLabel jLabel15;
    // End of variables declaration//GEN-END:variables
}